# Generated by Django 4.0.5 on 2022-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='rut',
            field=models.CharField(max_length=15),
        ),
    ]
