# Generated by Django 4.0.5 on 2022-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño_Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('direccion', models.TextField()),
                ('RANGOS_ADOPCION', models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Conocedor', 'Conocedor'), ('Cuidador', 'Cuidador'), ('Especialista', 'Especialista')], max_length=50)),
            ],
        ),
    ]
