# Generated by Django 4.0.5 on 2022-06-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dueño_Mascota',
            new_name='DuenoMascota',
        ),
    ]
